services:
  - type: web
    name: cinebook
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cinebook-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
    autoDeploy: true

databases:
  - name: cinebook-db
    databaseName: cinebook
    plan: free
